from __future__ import annotations


BASE_VARIABLES = {
    "APP_TIMEZONE", "LOG_LEVEL",
    "JIRA_SERVER_URL", "JIRA_AUTH_MODE", "JIRA_VERIFY_SSL", "JIRA_INCLUDE_SUBTASKS",
    "FIGMA_ENABLE_EXTRACTION", "FIGMA_EXTRACT_SCOPE", "FIGMA_ALLOW_FIRST_PAGE_FALLBACK",
    "FIGMA_MAX_FILES_PER_TICKET", "FIGMA_MAX_LAYERS_PER_PAGE", "FIGMA_MAX_SCREENS_PER_LAYER",
    "FIGMA_MAX_SCREENS_PER_PAGE", "FIGMA_MAX_LAYER_AREA", "FIGMA_MAX_LAYER_WIDTH",
    "FIGMA_MAX_LAYER_HEIGHT", "FIGMA_MIN_FRAME_WIDTH", "FIGMA_MIN_FRAME_HEIGHT",
    "FIGMA_MAX_FRAME_AREA", "FIGMA_MAX_FRAME_WIDTH", "FIGMA_MAX_FRAME_HEIGHT",
    "FIGMA_PAGE_RESOLVE_DEPTH", "FIGMA_PAGE_FETCH_DEPTH", "FIGMA_LAYER_FETCH_DEPTH",
    "FIGMA_LAYER_SCAN_DEPTH", "FIGMA_IMAGE_EXPORT_BATCH_SIZE", "FIGMA_EXPORT_SCALE",
    "FIGMA_EXPORT_FORMAT", "FIGMA_EXPORT_CONTAINER_LAYERS",
    "SANITIZE_REQUIREMENT", "REDACT_EMAILS", "REDACT_USERS", "REDACT_ORGANIZATIONS",
    "REDACT_URLS", "REQUIREMENT_CHUNK_MAX_CHARS", "REQUIREMENT_COMPACT_CONTEXT_MAX_CHARS",
    "REQUIREMENT_COMPACT_MAX_TEXT_ITEMS_PER_SCREEN", "REQUIREMENT_COMPACT_MAX_SCREEN_NAMES_PER_SECTION",
    "REQUIREMENT_COMPACT_MAX_KEY_TEXTS_PER_SECTION", "REQUIREMENT_COMPACT_MAX_ACTIONS_PER_SECTION",
    "REQUIREMENT_COMPACT_MAX_QA_NOTES_PER_SECTION", "REQUIREMENT_COMPACT_MAX_SCREENS_PER_SECTION_IN_MARKDOWN",
    "IMPROVE_FAIL_FAST", "IMPROVE_JSON_REPAIR_ENABLED", "TESTCASE_PARALLEL_WORKERS",
    "TESTCASE_SCENARIO_BATCH_SIZE", "TESTCASE_BATCH_PARALLEL_WORKERS", "MAX_STRUCTURE_REVIEW_ITERATIONS",
    "SCENARIO_STRUCTURE_BATCH_SIZE", "SCENARIO_PARALLEL_WORKERS", "COVERAGE_REVIEW_PARALLEL_WORKERS",
    "FINAL_REVIEW_PARALLEL_WORKERS", "IMPROVE_TESTCASE_PARALLEL_WORKERS", "INCREMENTAL_MAJOR_CHANGE_THRESHOLD",
    "CHAT_MAX_UPLOAD_MB", "CHAT_MAX_EXTRACTED_CHARS", "CHAT_HISTORY_MAX_MESSAGES",
    "CHAT_SESSIONS_DIR", "CHAT_UNLOCK_TOKEN_TTL_HOURS", "KNOWLEDGE_SYSTEM_ENABLED",
    "KNOWLEDGE_SYSTEM_LINK_TARGET", "KNOWLEDGE_SYSTEM_CONFIG_PATH", "KNOWLEDGE_SYSTEM_PROJECTS_JSON",
    "KNOWLEDGE_SYSTEM_ALLOW_HTTP",
}

AI_VARIABLES = {
    "TELEGRAM_AI_MODE", "PORTAL_DEFAULT_AI_MODE", "NON_PORTAL_AI_MODE",
    "MAX_CLARIFICATIONS_PER_ROUND", "MAX_CLARIFICATION_ROUNDS", "MODEL_PROVIDER",
    "DEEPSEEK_MODEL", "DEEPSEEK_BASE_URL", "DEEPSEEK_TIMEOUT", "ALLOW_DEEPSEEK_PRO",
    "FORCE_DISABLE_DEEPSEEK", "COPILOT_BASE_URL", "COPILOT_MODEL", "COPILOT_TIMEOUT",
    "FORCE_DISABLE_COPILOT", "LOCAL_AI_PROVIDER", "LOCAL_BASE_URL", "LOCAL_TEXT_MODEL",
    "LOCAL_COMPACT_MODEL", "LOCAL_VISION_MODEL", "LOCAL_TEXT_TIMEOUT", "LOCAL_COMPACT_TIMEOUT",
    "LOCAL_VISION_TIMEOUT", "FORCE_DISABLE_LOCAL_AI", "MAX_CONCURRENT_LLM_CALLS",
    "MAX_CONCURRENT_DEEPSEEK_CALLS", "MAX_CONCURRENT_COPILOT_CALLS", "MAX_CONCURRENT_LOCAL_CALLS",
    "LLM_HEALTH_CHECK_TIMEOUT", "LLM_CONCURRENCY_WAIT_TIMEOUT", "LLM_CONCURRENCY_RETRY_COUNT",
    "LLM_CONCURRENCY_RETRY_DELAY_SECONDS", "MAX_DEEPSEEK_CALLS_PER_JOB",
    "MAX_DEEPSEEK_INPUT_TOKENS_PER_JOB", "MAX_DEEPSEEK_OUTPUT_TOKENS_PER_JOB",
    "AI_DRY_RUN", "AI_USAGE_LOG_PATH",
}

QA_VARIABLES = {
    "KNOWLEDGE_BASE_ENABLED", "KNOWLEDGE_BASE_ROOT", "KNOWLEDGE_BASE_MAX_FILE_SIZE_BYTES",
    "KNOWLEDGE_BASE_DEFAULT_TOP_K", "STRUCTURED_ANALYSIS_ENABLED", "STRUCTURED_ANALYSIS_SHADOW_MODE",
    "KB_PACKAGE_MAX_COMPRESSED_SIZE_BYTES", "KB_PACKAGE_MAX_UNCOMPRESSED_SIZE_BYTES",
    "KB_PACKAGE_MAX_FILE_COUNT", "KB_PACKAGE_MAX_DIRECTORY_DEPTH",
    "KB_PACKAGE_MAX_COMPRESSION_RATIO", "KB_PACKAGE_ALLOWED_ARCHIVE_TYPES",
    "REQUIREMENT_QUALITY_GATE_ENABLED", "REQUIREMENT_QUALITY_GATE_MODE", "REQUIREMENT_QUALITY_LLM_REVIEW_ENABLED",
    "KNOWLEDGE_RETRIEVAL_ENABLED", "KNOWLEDGE_RETRIEVAL_SHADOW_MODE",
    "KNOWLEDGE_AUTO_RETRIEVAL_MAX_QUERIES", "KNOWLEDGE_AUTO_RETRIEVAL_TOP_K",
    "KNOWLEDGE_AUTO_RETRIEVAL_MAX_RESULTS", "KNOWLEDGE_AUTO_RETRIEVAL_MAX_SELECTED",
    "KNOWLEDGE_AUTO_RETRIEVAL_MAX_CONTEXT_CHARS", "KNOWLEDGE_AUTO_RETRIEVAL_MAX_QUERY_CHARS",
    "KNOWLEDGE_AUTO_RETRIEVAL_MIN_SCORE",
    "KNOWLEDGE_REFERENCE_REVIEW_REQUIRED", "KNOWLEDGE_REFERENCE_REVIEWER_IDS",
    "KNOWLEDGE_REFERENCE_REVIEW_LLM_CONFLICT_ASSIST", "KB_ANALYSIS_ENRICHMENT_MODE",
    "COVERAGE_MODEL_MODE", "TEST_CASE_GENERATOR_VERSION", "TEST_QUALITY_REVIEW_ENABLED",
    "TEST_QUALITY_REVIEW_MODE", "TEST_QUALITY_REVIEW_AI_MODE", "TEST_QUALITY_REVIEW_MODEL",
    "TEST_QUALITY_CORRECTOR_AI_MODE", "TEST_QUALITY_CORRECTOR_MODEL", "TRACEABILITY_GATE_ENABLED",
    "EXPORT_QUALITY_GATE_ENABLED", "EXPORT_QUALITY_GATE_MODE", "EXPORT_GATE_BLOCK_UNRESOLVED_BLOCKERS",
    "EXPORT_GATE_BLOCK_UNCOVERED_ACCEPTANCE_CRITERIA", "EXPORT_GATE_BLOCK_UNCOVERED_MANDATORY_COVERAGE",
    "EXPORT_GATE_BLOCK_UNSUPPORTED_EXPECTED_RESULTS", "EXPORT_GATE_BLOCK_UNREVIEWED_CONFLICTS",
    "EXPORT_GATE_BLOCK_MISSING_TRACEABILITY", "EXPORT_GATE_BLOCK_MISSING_QA_APPROVAL",
    "EXPORT_GATE_QA_LEAD_IDS", "QA_FEEDBACK_REVIEWER_IDS", "GOLDEN_DATASET_REVIEWER_IDS",
    "REQUIREMENT_ANALYZER_VERSION", "KNOWLEDGE_RETRIEVAL_VERSION", "KNOWLEDGE_RANKING_VERSION",
}

SECRET_VARIABLES = {
    "DEEPSEEK_API_KEY", "COPILOT_API_KEY", "TELEGRAM_BOT_TOKEN", "FIGMA_ACCESS_TOKEN",
    "JIRA_PAT", "JIRA_API_TOKEN", "JIRA_USERNAME", "JIRA_PASSWORD", "GITHUB_TOKEN",
    "KNOWLEDGE_BASE_MAINTAINER_TOKEN",
}

DEPRECATED_VARIABLES = {"COVERAGE_MODEL_ENABLED"}

VARIABLE_OWNER = {
    **{key: ".env" for key in BASE_VARIABLES},
    **{key: ".env.ai" for key in AI_VARIABLES},
    **{key: ".env.qa" for key in QA_VARIABLES},
    **{key: ".env.secrets" for key in SECRET_VARIABLES},
}
KNOWN_VARIABLES = set(VARIABLE_OWNER) | DEPRECATED_VARIABLES

CANONICAL_AI_MODES = {
    "TEST_LOCAL_ONLY", "PRODUCTION_HYBRID_DEEPSEEK", "PRODUCTION_HYBRID_COPILOT",
    "DEEPSEEK_ONLY", "COPILOT_ONLY", "NO_LLM",
}
DEPRECATED_AI_MODES = {"PRODUCTION_HYBRID", "PRODUCTION_REMOTE_ONLY"}

ENUM_VALUES = {
    "TELEGRAM_AI_MODE": CANONICAL_AI_MODES | DEPRECATED_AI_MODES,
    "PORTAL_DEFAULT_AI_MODE": CANONICAL_AI_MODES | DEPRECATED_AI_MODES,
    "NON_PORTAL_AI_MODE": CANONICAL_AI_MODES | DEPRECATED_AI_MODES | {""},
    "JIRA_AUTH_MODE": {"PAT", "BASIC"},
    "FIGMA_EXTRACT_SCOPE": {"linked_page", "linked_node", "file"},
    "FIGMA_EXPORT_FORMAT": {"png", "jpg", "svg", "pdf"},
    "REQUIREMENT_QUALITY_GATE_MODE": {"off", "warn", "block_on_critical"},
    "KB_ANALYSIS_ENRICHMENT_MODE": {"off", "shadow", "manual", "automatic"},
    "COVERAGE_MODEL_MODE": {"off", "shadow", "enabled"},
    "TEST_CASE_GENERATOR_VERSION": {"v1", "v2-shadow", "v2-manual", "v2"},
    "TEST_QUALITY_REVIEW_MODE": {"off", "warn", "block_export"},
    "EXPORT_QUALITY_GATE_MODE": {"warn", "block"},
}
