from typing import TypedDict, NotRequired


class QAState(TypedDict):
    ticket_id: str

    requirement_context: NotRequired[str]
    requirement_context_metadata: NotRequired[dict]
    jira_issue_key: NotRequired[str]
    jira_project_key: NotRequired[str]
    knowledge_base_id: NotRequired[str]
    knowledge_snapshot_id: NotRequired[str]
    knowledge_retrieval_status: NotRequired[str]
    knowledge_context: NotRequired[str]
    knowledge_references: NotRequired[list[dict]]
    knowledge_warnings: NotRequired[list[str]]
    analysis_run_id: NotRequired[str]

    analysis: NotRequired[dict]
    structured_analysis: NotRequired[dict]
    structured_analysis_metadata: NotRequired[dict]
    structured_analysis_error: NotRequired[str]
    quality_gate: NotRequired[dict]
    quality_report: NotRequired[dict]
    quality_report_error: NotRequired[str]
    enrichment: NotRequired[dict]
    enriched_analysis: NotRequired[dict]
    enrichment_diff: NotRequired[dict]
    enrichment_approval: NotRequired[dict]
    active_enriched_analysis: NotRequired[dict]
    coverage_model_run: NotRequired[dict]
    coverage_model: NotRequired[dict]
    coverage_analysis: NotRequired[str]
    active_coverage_model: NotRequired[dict]
    coverage_model_error: NotRequired[dict]
    requirement_qa: NotRequired[dict]
    clarifications: NotRequired[dict]
    clarification_answers: NotRequired[dict]
    requirement_summary: NotRequired[dict]
    test_scope: NotRequired[dict]

    generation_mode: NotRequired[str]
    ai_mode: NotRequired[str]
    source_channel: NotRequired[str]
    approved_test_case_structure: NotRequired[dict]

    scenarios: NotRequired[list]
    testcases: NotRequired[list]
    testcases_v2: NotRequired[dict]
    testcases_v2_reviewed: NotRequired[dict]
    generator_comparison: NotRequired[dict]
    test_case_generator_run: NotRequired[dict]
    testcases_v2_error: NotRequired[dict]
    test_quality_report: NotRequired[dict]
    correction_history: NotRequired[dict]
    test_quality_review_run: NotRequired[dict]
    automation_testcases: NotRequired[list]
    manual_testcases: NotRequired[list]

    function_testcase_results: NotRequired[list]
    function_generation_manifest_file: NotRequired[str]

    coverage_review: NotRequired[dict]
    function_coverage_results: NotRequired[list]
    function_coverage_manifest_file: NotRequired[str]

    improved_testcases: NotRequired[list]
    function_improve_results: NotRequired[list]
    function_improve_manifest_file: NotRequired[str]

    final_coverage_review: NotRequired[dict]
    function_final_review_results: NotRequired[list]
    function_final_review_manifest_file: NotRequired[str]

    excel_file: NotRequired[str]
